LRU Cache using clds_hash_table, SRW Lock and DList
Azure/clds pull request #177
Opened 2023-09-11 11:02 UTC by cyrus-jackson

Implementation for LRU Cache. The design doc is [here](https://github.com/Azure/clds/blob/master/devdoc/lru_cache_design.md)

`put` :
![image](https://github.com/Azure/clds/assets/20659664/e83e3b95-4fd8-4dd1-a045-1522284e4fd8)

`Eviction logic`: 
![image](https://github.com/Azure/clds/assets/20659664/5bd69d7e-14fd-43cd-b5a2-08361d844fe4)

`get`:
![image](https://github.com/Azure/clds/assets/20659664/b1f1fc78-57ce-4e08-9289-f6e7a7ac5be2)

The operations to clds_hash_table are done under a lock to make sure there are no race conditions

2023-09-27 15:39 UTC, avranju commented on devdoc/lru_cache_requirements.md
> +typedef void(*LRU_CACHE_EVICT_CALLBACK_FUNC)(void* context, LRU_CACHE_EVICT_RESULT cache_evict_status);
Should we pass a reference to the item being evicted in the callback?

2023-09-27 15:39 UTC, avranju commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_010: [** If `capacity` is less than or equals to `0`, then `lru_cache_create` shall fail and return NULL. **]**
Should we make `capacity` an unsigned value?

2023-09-27 15:39 UTC, avranju commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_021: [** If `lru_cache` is `NULL`, then `lru_cache_destroy` shall fail. **]**
Being a function that returns `void` what does "shall fail" mean? Is the idea that we will terminate the process?

2023-09-27 15:39 UTC, avranju commented on devdoc/lru_cache_requirements.md
> +The `lru_cache_put` function is utilized for inserting or updating an item in the Least Recently Used (LRU) cache. If the item already exists in the cache, it is removed and reinserted to maintain th
> If the item already exists in the cache, it is removed and reinserted to maintain the LRU order

I think Achintya had the opinion that we should be able to just update the item in place in the hash table without needing to remove and re-insert it.

2023-09-27 15:39 UTC, avranju commented on devdoc/lru_cache_requirements.md
> +The `lru_cache_put` function is utilized for inserting or updating an item in the Least Recently Used (LRU) cache. If the item already exists in the cache, it is removed and reinserted to maintain th
> when the cache is at full capacity

What does `capacity` mean here? I don't suppose we have insight into actual memory use do we? As in, the "items" stored in the hash table are just pointers to us aren't they? Do we know how big the memory is that they are pointing to? Or is `capacity` just a count of items in the hash table? Would such a count based control measure enable us to bound memory use in the cache?

2023-09-27 15:39 UTC, avranju commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_026: [** If `size` is `0`, then `lru_cache_put` shall fail and return `LRU_CACHE_PUT_ERROR`. **]**
Ok, so we do know what the size of the item is. :)

2023-09-27 15:39 UTC, avranju commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_047: [** `lru_cache_put` shall append the node to the tail and update the `current_size` with item `size`. **]**
Should this be 2 requirements? Append to linked list and increment current size?

2023-09-27 15:39 UTC, avranju commented on tests/CMakeLists.txt
> +	    build_test_folder(lru_cache_int)
Why only Win32 for int test?

2023-09-27 15:39 UTC, avranju commented on src/lru_cache.c
> +// Licensed under the MIT license.See LICENSE file in the project root for full license information.
Copyright notice?

2023-10-16 17:41 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +MOCKABLE_FUNCTION(, LRU_CACHE_HANDLE, lru_cache_create, COMPUTE_HASH_FUNC, compute_hash, KEY_COMPARE_FUNC, key_compare_func, size_t, initial_bucket_size, CLDS_HAZARD_POINTERS_HANDLE, clds_hazard_poin
>capacity [](http://example.com/codeflow?start=346&length=8)

should this be `capacity_bytes`?

2023-10-16 17:43 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +MOCKABLE_FUNCTION(, CLDS_HASH_TABLE_ITEM*, lru_cache_get, LRU_CACHE_HANDLE, lru_cache, void*, key);
Probably want a way to remove items rather than only waiting for them to get evicted.

2023-10-16 17:43 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +A cache module that deletes the least-recently-used (lru) items. The design for this is [here]()
>[here]() [](http://example.com/codeflow?start=88&length=8)

nit: missing link

2023-10-16 17:43 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_001: [** If `compute_hash` is NULL, `lru_cache_create` shall fail and return NULL. **]**
>NULL [](http://example.com/codeflow?start=49&length=4)

missing backticks, here and everywhere

2023-10-16 17:44 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_018: [** `lru_cache_create` shall assign default value of `0` to `current_size` and `capacity`. **]**
>capacity [](http://example.com/codeflow?start=104&length=8)

why would it assign 0 to capacity?

2023-10-16 17:45 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_021: [** If `lru_cache` is `NULL`, then `lru_cache_destroy` shall fail. **]**
> We dont terminate the process (should we?). 

We shouldn't.

2023-10-16 17:47 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +The `lru_cache_put` function is utilized for inserting or updating an item in the Least Recently Used (LRU) cache. If the item already exists in the cache, the `current_size` is updated first, and th
>add_to_cache_internal [](http://example.com/codeflow?start=368&length=21)

name here is implementation detail, not needed, can just say "...it adds the item to the cache and performs..."

2023-10-16 17:48 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +The `lru_cache_put` function is utilized for inserting or updating an item in the Least Recently Used (LRU) cache. If the item already exists in the cache, the `current_size` is updated first, and th
>evict_internal [](http://example.com/codeflow?start=432&length=14)

Do you want to spec this out separately (because you talked about maybe making it happen on a worker thread later)? If not, we can remove the name here as well.

2023-10-16 17:49 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +Note: The `size` of the value needs to be precalculated in terms of the `capacity` mentioned at the creation of the cache.
Ah I see, size/capacity don't have units, they just need to match (either just a count, or actual size in bytes or something else).

2023-10-16 17:51 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +Note: The `size` of the value needs to be precalculated in terms of the `capacity` mentioned at the creation of the cache.
All of the description here is a bit long. Typically these sorts of explanations belong at top of the document somewhere after the overview in something like a "design details" section.

That section(s) can define the logic of when the size is updated/compared to capacity, how eviction works, what capacity means, etc.

2023-10-16 17:56 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +- **SRS_LRU_CACHE_13_065: [** `lru_cache_put` shall update the LRU Node item in the hash table by calling `clds_hash_table_set_value`. **]**
This is inherently racey. The item may be removed between the check in 13_029 and the update in 13_065 and we need to handle this.

Also, I thought we said we would want to  to the order of updates as:
1. Update CLDS
2. Update list
3. Update size

And the eviction checks in the reverse order:
1. Check size
2. Get node from list
3. Remove from CLDS

I think that ordering makes more sense because then the eviction will only look at the structures if it knows the size has changed. In the reverse case, eviction is lookin at the LRU list before the new item has actually be inserted.

2023-10-16 17:57 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +- **SRS_LRU_CACHE_13_065: [** `lru_cache_put` shall update the LRU Node item in the hash table by calling `clds_hash_table_set_value`. **]**
So maybe we need to instead do this:

1. clds_hash_table_set_value
2. update list
3. Check if we replaced an item
4. Update size (adding new size and removing old if it was replaced).

2023-10-16 17:58 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_037: [** While the `capacity` of the cache is full: **]**
>e `capacity` of the cache is full: * [](http://example.com/codeflow?start=36&length=36)

poetry: the capacity doesn't change so to say "while the capacity is full" doesn't make much sense. Likely want "While the current size of the cache exceeds `capacity`:"

2023-10-16 17:58 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +- **SRS_LRU_CACHE_13_038: [** `lru_cache_put` shall get the least used node. **]**
>get the least used node. **] [](http://example.com/codeflow?start=52&length=28)

Maybe this should say something about the head of the LRU list

2023-10-16 18:01 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +- **SRS_LRU_CACHE_13_074: [** `lru_cache_put` shall release the lock in exclusive mode. **]**
We are leaving the node in the list during the clds remove? This seems to have extra complexity and races (two evictions could pull the same node and both try to remove it).

Instead I think we should be removing it around 13_038 (get the LRU node and remove it all in one critical section).

2023-10-16 18:12 UTC, mattdurak commented on devdoc/lru_cache_requirements.md
> +- **SRS_LRU_CACHE_13_057: [** `lru_cache_get` shall remove the old value node from `doubly_linked_list` by calling `DList_RemoveEntryList`. **]**
>old value node from `doubly_linked_list` by calling `DList_RemoveEntryList`. **]** [](http://example.com/codeflow?start=63&length=82)

This needs to handle the node getting removed already, likely the node needs some additional state that says whether it has been removed from the list and that needs to be used under the same lock.

2023-10-16 18:13 UTC, mattdurak commented on inc/clds/lru_cache.h
> +MOCKABLE_FUNCTION(, LRU_CACHE_HANDLE, lru_cache_create, COMPUTE_HASH_FUNC, compute_hash, KEY_COMPARE_FUNC, key_compare_func, size_t, initial_bucket_size, CLDS_HAZARD_POINTERS_HANDLE, clds_hazard_poin
>volatile_atomic [](http://example.com/codeflow?start=205&length=15)

missing c_pal/interlocked.h include

2023-10-16 18:13 UTC, mattdurak commented on inc/clds/lru_cache.h
> +#include "umock_c/umock_c_prod.h"
nit: this should be last

2023-10-16 18:14 UTC, mattdurak commented on inc/clds/lru_cache.h
> +MU_DEFINE_ENUM(LRU_CACHE_PUT_RESULT, LRU_CACHE_PUT_RESULT_VALUES);
>MU_DEFINE_ENUM [](http://example.com/codeflow?start=0&length=14)

missing macro utils include

2023-10-16 18:14 UTC, mattdurak commented on tests/lru_cache_int/lru_cache_int.c
> +#define XTEST_FUNCTION(A) void A(void)
>XTEST_FUNCTION [](http://example.com/codeflow?start=8&length=14)

should probably be removed

2023-10-16 18:15 UTC, mattdurak commented on tests/lru_cache_int/lru_cache_int.c
> +END_TEST_SUITE(TEST_SUITE_NAME_FROM_CMAKE)
are chaos tests coming in a separate PR? There are a lot of potential races here that we should have tests for.

2023-10-16 21:51 UTC, mattdurak commented on src/lru_cache.c
> +                interlocked_exchange_64(lru_cache->seq_no, 0);
>interlocked_exchange_64(lru_cache->seq_no, 0); [](http://example.com/codeflow?start=16&length=46)

Looks like an uninitialized pointer. If we really want to make it optional, then this structure needs a `int64_t` field backing this.

But do we need to make it optional? Can we decide if we need the sequence number and require it, or don't need it and don't even take it as a parameter?

2023-10-16 21:51 UTC, mattdurak commented on src/lru_cache.c
> +                    lru_cache->lock = srw_lock_create(false, "lru_cache_lock");
>srw_lock_create [](http://example.com/codeflow?start=38&length=15)

consider srw_lock_ll if we don't care about statistics (since we are passing false).

2023-10-16 21:53 UTC, mattdurak commented on src/lru_cache.c
> +        //clds_hazard_pointers_destroy(lru_cache->clds_hazard_pointers);
>//clds_hazard_pointers_destroy(lru_cache->clds_hazard_pointers); [](http://example.com/codeflow?start=8&length=64)

remove

2023-10-26 03:04 UTC, dcristoloveanu commented
> 1. The table contains `LRU_NODE` instances as the value corresponding to the supplied keys. The `LRU_NODE` contains a `DLIST_ENTRY` which points to a node in the `doubly_linked_list`. A pointer to the `LRU_NODE` is stored in the `doubly_linked_list` as well.

technically it does not point - as in it does not have a pointer to an item. It is an anchor for doubly linked list purposes, because it is part of a structure that the doubly linked list does not know about.

---
Refers to: devdoc/lru_cache_design.md:41 in 706a111. [](commit_id = 706a111b1018b69db6130315189ab04a5e7cd6a4, deletion_comment = False)

2023-10-26 03:05 UTC, dcristoloveanu commented
> 1. The table contains `LRU_NODE` instances as the value corresponding to the supplied keys. The `LRU_NODE` contains a `DLIST_ENTRY` which points to a node in the `doubly_linked_list`. A pointer to the `LRU_NODE` is stored in the `doubly_linked_list` as well.

I think this is creating confusion. It is by the use of the DLIST_ENTRY that the nodes can be tracked in the DLIST.

---
Refers to: devdoc/lru_cache_design.md:41 in 706a111. [](commit_id = 706a111b1018b69db6130315189ab04a5e7cd6a4, deletion_comment = False)

2023-10-26 03:07 UTC, dcristoloveanu commented on devdoc/lru_cache_design.md
> +The eviction process involves updating the cache's current size, removing the least recently used item, and invoking an eviction callback. All the latest items are inserted at the tail of the `doubly
>t`. Dur [](http://example.com/codeflow?start=210&length=7)

Can we please lean on the keyboard and get some CRLFs between paragraphs? Makes it easier to read the .md :-).

2023-10-26 03:11 UTC, dcristoloveanu commented on devdoc/lru_cache_requirements.md
> +MOCKABLE_FUNCTION(, LRU_CACHE_HANDLE, lru_cache_create, COMPUTE_HASH_FUNC, compute_hash, KEY_COMPARE_FUNC, key_compare_func, size_t, initial_bucket_size, CLDS_HAZARD_POINTERS_HANDLE, clds_hazard_poin
>size_t [](http://example.com/codeflow?start=125&length=6)

Can we use uint32_t?

2023-10-26 03:13 UTC, dcristoloveanu commented on devdoc/lru_cache_requirements.md
> +The `lru_cache_put` function is utilized for inserting or updating an item in the Least Recently Used (LRU) cache. If the item already exists in the cache, the `current_size` is updated first, and th
>he  and p [](http://example.com/codeflow?start=358&length=9)

Extra space

2023-10-26 03:14 UTC, dcristoloveanu commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_016: [** `lru_cache_create` shall allocate `SRW_LOCK_LL` by calling `srw_lock_ll_init`. **]**
>allocate [](http://example.com/codeflow?start=53&length=8)

The proper term would be initialize since it is a SRW_LOCK_LL

2023-10-26 03:14 UTC, dcristoloveanu commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_017: [** `lru_cache_create` shall initialize `head` by calling `DList_InitializeListHead`. **]**
> `head` [](http://example.com/codeflow?start=63&length=7)

Consider saying "initialize the doubly linked list". head is very specific with regards to the field used in the code.

2023-10-26 03:15 UTC, dcristoloveanu commented on devdoc/lru_cache_requirements.md
> +**SRS_LRU_CACHE_13_018: [** `lru_cache_create` shall assign default value of `0` to `current_size` and the capacity to `capacity`. **]**
>default [](http://example.com/codeflow?start=60&length=7)

I think default does not add any value here. assign 0 is very clear.

2023-10-26 03:16 UTC, dcristoloveanu commented on src/lru_cache.c
> +#include <stdbool.h>
Not needed

2023-10-26 03:17 UTC, dcristoloveanu commented on src/lru_cache.c
> +#include "c_util/rc_string.h"
Not needed

2023-10-26 03:17 UTC, dcristoloveanu commented on src/lru_cache.c
> +#include "c_pal/thandle.h"
Also not needed

2023-10-26 03:17 UTC, dcristoloveanu commented on src/lru_cache.c
> +
Nitpick: Usually we go in the order
c_logging
c_pal
c_util
clds
...

These seem to be a bit intertwined.

2023-10-26 03:18 UTC, dcristoloveanu commented on src/lru_cache.c
> +    uint64_t capacity;
>uint64_t [](http://example.com/codeflow?start=4&length=8)

I find it weird that capacity is uint64_t and size is int64_t. Isn't there a gap?

2023-10-26 03:18 UTC, dcristoloveanu commented on src/lru_cache.c
> +    volatile_atomic int32_t state; /* LRU_NODE_STATE */
>/* LRU_NODE_STATE */ [](http://example.com/codeflow?start=35&length=20)

Nice

2023-10-26 03:20 UTC, dcristoloveanu commented on src/lru_cache.c
> +                        result = NULL;
> result = NULL; [](http://example.com/codeflow?start=23&length=15)

I think you can simply have result = NULL between lines 140 and 141 and then it is not repeated in each if.

2023-10-26 03:21 UTC, dcristoloveanu commented on src/lru_cache.c
> +        (void)interlocked_add_64(&lru_cache->current_size, size);
>ache->current_size, size); [](http://example.com/codeflow?start=39&length=26)

Can this overflow?

2023-10-26 03:22 UTC, dcristoloveanu commented on src/lru_cache.c
> +        if (result != LRU_CACHE_EVICT_OK || (uint64_t)current_size <= lru_cache->capacity)
>(uint64_t) [](http://example.com/codeflow?start=44&length=10)

Meh, this is what I was talking about with the difference in types a bit earlier.

2023-10-26 03:23 UTC, dcristoloveanu commented on src/lru_cache.c
> +            LRU_NODE* least_used_node_value = (LRU_NODE*)CONTAINING_RECORD(least_used_node, LRU_NODE, node);
>(LRU_NODE*) [](http://example.com/codeflow?start=46&length=11)

What happens if you remove the cast?

2023-10-26 03:25 UTC, dcristoloveanu commented on src/lru_cache.c
> +            if (interlocked_compare_exchange_64(&lru_cache->current_size, current_size - least_used_node_value->size, current_size) != current_size)
>current_size - least_used_node_value->size [](http://example.com/codeflow?start=74&length=42)

Can this underflow? We should check/have tests for it.

2023-10-26 03:26 UTC, dcristoloveanu commented on src/lru_cache.c
> +                                (void)DList_RemoveEntryList(least_used_node);
>       (void)DList_RemoveEntryList(least_used_node); [](http://example.com/codeflow?start=25&length=52)

Somewhere around here we should have a LogVerbose

2023-10-26 03:26 UTC, dcristoloveanu commented on src/lru_cache.c
> +                                (void)DList_RemoveEntryList(least_used_node);
Otherwise figuring out what happened in PROD will be tough.

2023-10-26 03:27 UTC, dcristoloveanu commented on src/lru_cache.c
> +            DLIST_ENTRY* least_used_node = lru_cache->head.Flink;
>least_used_node [](http://example.com/codeflow?start=25&length=15)

This least used node is saved here under the lock.
And then it is later used in ln 262.
I don't think it can be absolutely guaranteed that it has not changed, can it?

2023-10-26 03:27 UTC, dcristoloveanu commented on src/lru_cache.c
> +            DLIST_ENTRY* least_used_node = lru_cache->head.Flink;
This smells like some AV waiting to happen.

2023-10-26 03:29 UTC, dcristoloveanu commented on src/lru_cache.c
> +
Between ln 216 and 232 there is no modification done, we're only reading the node (questionable if that's all we should do). But if we only read, why would we acquire the lock exclusively?

2023-10-26 03:30 UTC, dcristoloveanu commented on src/lru_cache.c
> +            {
I don't think we should proceed with executing with hazard_pointers_thread being NULL.

2023-10-26 03:32 UTC, dcristoloveanu commented on src/lru_cache.c
> +
Why is this needed? I think it is not. And has no spec. I suspect that you wrote the code first?

If that is the case, we should discuss :-). I'd like to clear the air around why we write tests first.

2023-10-26 03:32 UTC, dcristoloveanu commented on src/lru_cache.c
> +
No shaming or anything, good topic for 1:1 :-D

2023-10-26 03:33 UTC, dcristoloveanu commented on src/lru_cache.c
> +                    srw_lock_ll_acquire_exclusive(&lru_cache->srw_lock);
>srw_lock_ll_acquire_exclusive [](http://example.com/codeflow?start=20&length=29)

I don't think we should acquire exclusive for a get operation.

2023-10-26 03:34 UTC, dcristoloveanu commented on src/lru_cache.c
> +void* lru_cache_get(LRU_CACHE_HANDLE lru_cache, void* key)
>void* [](http://example.com/codeflow?start=0&length=5)

While looking at this I thought: wouldn't this be nice to be templatized :-)? A wild consider obviously.

2023-10-26 03:34 UTC, dcristoloveanu commented on src/lru_cache.c
> +            if (hash_table_item != NULL)
>  if (hash_table_item != NULL) [](http://example.com/codeflow?start=10&length=30)

On the else branch we should probably LogVerbose.

2023-10-26 03:35 UTC, dcristoloveanu commented on src/lru_cache.c
> +                    {
> { [](http://example.com/codeflow?start=19&length=2)

Likely not needed

2023-10-26 03:37 UTC, dcristoloveanu commented on src/lru_cache.c
> +                            DList_InitializeListHead(node);
Highly unnecessary

2023-10-26 03:38 UTC, dcristoloveanu commented on tests/lru_cache_int/lru_cache_int.c
> +#include <stdbool.h>
Not needed

2023-10-26 03:38 UTC, dcristoloveanu commented on tests/lru_cache_int/lru_cache_int.c
> +void on_evict_callback(void* context, LRU_CACHE_EVICT_RESULT cache_evict_status, void* item)
>on_evict_callback [](http://example.com/codeflow?start=5&length=17)

Likely static

2023-10-26 03:40 UTC, dcristoloveanu commented on tests/lru_cache_int/lru_cache_int.c
> +TEST_FUNCTION(test_put_same_key_calls_evict_to_make_space)
>test_put_same_key_calls_evict_to_make_space [](http://example.com/codeflow?start=14&length=43)

We have to add a chaos int test.
No way we should ship this new cache without that. Keep a counter of what it finds :-).

2023-10-26 03:40 UTC, dcristoloveanu commented on tests/lru_cache_int/lru_cache_int.c
> +    CLDS_HASH_TABLE_ITEM** items = malloc(n * sizeof(CLDS_HASH_TABLE_ITEM*));
>malloc [](http://example.com/codeflow?start=35&length=6)

This should be malloc_2

2023-10-26 03:41 UTC, dcristoloveanu commented on tests/lru_cache_int/lru_cache_int.c
> +        items[i] = CLDS_HASH_TABLE_NODE_CREATE(TEST_ITEM, NULL, NULL);
>items[i] [](http://example.com/codeflow?start=8&length=8)

Missing ASSERT_IS_NOT_NULL

2023-10-26 03:41 UTC, dcristoloveanu commented on tests/lru_cache_int/lru_cache_int.c
> +    CLDS_HASH_TABLE_ITEM* large_item = CLDS_HASH_TABLE_NODE_CREATE(TEST_ITEM, NULL, NULL);
>large_item [](http://example.com/codeflow?start=26&length=10)

Missing ASSERT_IS_NOT_NULL.

2023-10-26 03:42 UTC, dcristoloveanu commented on tests/lru_cache_int/lru_cache_int.c
> +    CLDS_HASH_TABLE_ITEM* item1 = CLDS_HASH_TABLE_NODE_CREATE(TEST_ITEM, NULL, NULL);
>item1 = CLDS_HASH_TABL [](http://example.com/codeflow?start=26&length=22)

Missing NULL assert. Here and everywhere.

2023-10-26 03:43 UTC, dcristoloveanu commented on tests/lru_cache_ut/lru_cache_ut.c
> +#include <stdbool.h>
Not needed. This and the umock ones for bool.

2023-10-26 03:44 UTC, dcristoloveanu commented on tests/lru_cache_ut/lru_cache_ut.c
> +
Usually it is easier to put this before checking the expected/actual calls. My experience at least. /consider.

2023-10-26 03:47 UTC, dcristoloveanu commented
I would like to see the next iteration because 2 items (which will require a push of a new commit anyway)
- Clearing the acquire_exclusive, get a pointer, release, acquire again, use the previous saved pointer issue in evict. I think releasing the lock and using a pointer that was saved is dangerous.
- chaos int test

2023-10-26 03:47 UTC, dcristoloveanu requested changes
:clock1:

2023-11-02 16:49 UTC, mattdurak commented on src/lru_cache.c
> +                    srw_lock_ll_acquire_exclusive(&lru_cache->srw_lock);
What if the item is evicted between the find and the lock acquire?

Can we avoid the find altogether and just always do `clds_hash_table_set_value` (and check if we have an `old_value` or not)?

2023-11-02 16:51 UTC, mattdurak commented on src/lru_cache.c
> +                    srw_lock_ll_acquire_exclusive(&lru_cache->srw_lock);
You have the same issue with the else branch where we might not find the item, then it gets inserted on another thread before we take the lock here.

2023-11-02 16:56 UTC, mattdurak commented on src/lru_cache.c
> +LRU_CACHE_PUT_RESULT lru_cache_put(LRU_CACHE_HANDLE lru_cache, void* key, void* value, int64_t size, LRU_CACHE_EVICT_CALLBACK_FUNC evict_callback, void* context)
>LRU_CACHE_EVICT_CALLBACK_FUNC evict_callback, void* context [](http://example.com/codeflow?start=101&length=59)

I'm reading this code more and now I'm confused. What is `evict_callback` meant to do?

My expectation: I pass `evict_callback` when I put an item with a key/value (call it X). When *that* item X is evicted some time later.

Apparent reality on line 430: I pass `evict_callback` when I put an item with a key/value (X) and if *that* put call causes some *other* item Y to be evicted, then my callback is called.

Why would the caller of put care about other items getting evicted?

2023-11-02 16:59 UTC, mattdurak commented on src/lru_cache.c
> +    volatile_atomic int32_t state; /* LRU_NODE_STATE */
I think this should have an eviction callback/context

2023-11-02 17:02 UTC, mattdurak commented on src/lru_cache.c
> +                evict_callback(context, LRU_CACHE_EVICT_ERROR, NULL);
>evict_callback(context, LRU_CACHE_EVICT_ERROR, NULL); [](http://example.com/codeflow?start=16&length=53)

See my other comment, but if we change it so each item has a callback, then I guess create would need an "on_error" callback for cases like this.

2023-11-02 17:03 UTC, mattdurak commented on src/lru_cache.c
> +                LogError("current_size is less 0. Failing eviction.");
>current_size is less [](http://example.com/codeflow?start=26&length=20)

really current_size minus the node size is less than 0. Should log those 2 values to understand why

2023-11-02 17:04 UTC, mattdurak commented on src/lru_cache.c
> +            if (interlocked_compare_exchange_64(&lru_cache->current_size, current_size - least_used_node_value->size, current_size) != current_size)
You may want to keep the underflow check to be defensive but leave out its spec/test if it's not possible to test it.

2023-11-02 17:06 UTC, mattdurak commented on src/lru_cache.c
> +                            }
If we always just lock for everything, do we even need this state anymore?

2023-11-02 17:09 UTC, mattdurak commented on src/lru_cache.c
> +                            evict_callback(context, LRU_CACHE_EVICT_ERROR, NULL);
>LRU_CACHE_EVICT_ERROR [](http://example.com/codeflow?start=52&length=21)

likely want to break out of the loop also here

2023-11-06 11:55 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    N --> O
Not need if the item is already present. any how we are not going to increase the size.

2023-11-06 11:55 UTC, ACKPaul commented on src/lru_cache.c
> +                    CLDS_HASH_TABLE_SET_VALUE_RESULT set_value_result = clds_hash_table_set_value(lru_cache->table, hazard_pointers_thread, key, item, NULL, NULL, &old_item, NULL);
"Why do we need to set a value here? I believe we're already reading a sealed block, and there's no chance of increasing the size. Inserting a value via the API should work fine, and all the size-related checks from the old block will become obsolete."

2023-11-06 11:55 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    M --> P
"I believe we're already reading a sealed block, and there's no chance of increasing the size.  I think this is not required.

2023-11-06 12:17 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    M --> P
"If we want to consider size, there should be a flag in the LRU cache creation, giving users the option to enable or disable it."

2023-11-06 12:17 UTC, ACKPaul commented on src/lru_cache.c
> +                    CLDS_HASH_TABLE_SET_VALUE_RESULT set_value_result = clds_hash_table_set_value(lru_cache->table, hazard_pointers_thread, key, item, NULL, NULL, &old_item, NULL);
"If we want to consider size, there should be a flag in the LRU cache creation, giving users the option to enable or disable it."

2023-11-06 18:07 UTC, mattdurak commented on src/lru_cache.c
> +        LogError("Invalid arguments: COMPUTE_HASH_FUNC compute_hash=%p, KEY_COMPARE_FUNC key_compare_func=%p, uint32_t initial_bucket_size=%u, CLDS_HAZARD_POINTERS_HANDLE clds_hazard_pointers=%p, int
>int64_t capacity=%" PRId64 "", [](http://example.com/codeflow?start=196&length=30)

missing on_error parameters

2023-11-06 18:09 UTC, mattdurak commented on src/lru_cache.c
> +        if (result != LRU_CACHE_EVICT_OK || current_size <= lru_cache->capacity)
>result != LRU_CACHE_EVICT_OK  [](http://example.com/codeflow?start=12&length=29)

nit: this could just be the "while" condition

2023-11-06 18:13 UTC, mattdurak commented on tests/lru_cache_int/lru_cache_int.c
> +// Cyrus
?

2023-11-06 18:21 UTC, mattdurak submitted a review, later dismissed
:shipit:

2023-11-08 17:22 UTC, mattdurak submitted a review, later dismissed
:shipit:

2023-11-09 17:03 UTC, mattdurak commented on tests/lru_cache_ut/lru_cache_ut.c
> +    ASSERT_IS_NOT_NULL(test_clds_hazard_pointers, "Cannot create hazard pointers");
>pointers [](http://example.com/codeflow?start=72&length=8)

thread helper

2023-11-09 17:05 UTC, mattdurak commented on tests/lru_cache_ut/lru_cache_ut.c
> +#include "c_pal/interlocked.h"
>interlocked [](http://example.com/codeflow?start=16&length=11)

maybe should have a todo comment with a task number to put this back in the mocks...

2023-11-09 17:05 UTC, mattdurak submitted a review, later dismissed
:shipit:

2023-11-11 05:24 UTC, dcristoloveanu approved these changes

2023-11-11 05:35 UTC, merged