LRU Cache Design
Azure/clds pull request #178
Opened 2023-09-13 03:11 UTC by cyrus-jackson

Design document for LRU Cache using CLDS_HASH_TABLE and doublylinkedlist from c_utils

2023-09-13 05:35 UTC, dcristoloveanu commented on devdoc/lru_cache_design.md
> +All operations can be concurrent with other operations of the same or different kinds.
Nice callout

2023-09-13 05:35 UTC, dcristoloveanu commented on devdoc/lru_cache_design.md
> +LRU Cache uses 2 `clds_hash_tables`, a `srw_lock`, and a `doubly_linked_list`.
>2 `clds_hash_tables` [](http://example.com/codeflow?start=15&length=20)

Funny comment: what's better than one hash table? 2 hashtables!

2023-09-13 05:41 UTC, dcristoloveanu commented on devdoc/lru_cache_design.md
> +To evict the least recently used item from the cache, the key from the tail of the `doubly_linked_list` is removed in both the tables (i.e., `link_table` and `item_table`), and the node is truncated
>`link_table` and `item_table`), and the node is truncated from the `doubly_linked_list`. [](http://example.com/codeflow?start=141&length=88)

There seems to be 3 operations needed.
Do we really need 3?

I am thinking of the following design (and maybe it doe snot work, but I shall brain dump it here):

We have a hash table - we want this to look up the blocks/kvps.
Each of these entries stored in the hash table has a dlist entry.
we have a dlist that gives the order.

I understand we need for put:
- craft entry
- insert in hash table
- lock list
- insert in list at head (flink)
- unlock list

For find:
- find in has table

For evict:
- lock list
- remove from tail (blink)
- unlock list
- remove from hash table the item

I don't see why we need the 3rd structure? Seems to complicate things. But maybe I am missing something.

2023-09-13 05:42 UTC, dcristoloveanu requested changes
:clock1:

2023-09-13 10:45 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    CLDS_HASH_TABLE_HANDLE item_table;
I think we do not need two hash Table. One Hash Table is good enough for LRU cache.

2023-09-13 10:45 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +To evict the least recently used item from the cache, the key from the tail of the `doubly_linked_list` is removed in both the tables (i.e., `link_table` and `item_table`), and the node is truncated
One question: What is the rationale for requiring an explicit eviction function? In my view, if a table or list is full when inserting data, it should automatically handle eviction without the need for explicit instructions.

2023-09-13 10:45 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +To evict the least recently used item from the cache, the key from the tail of the `doubly_linked_list` is removed in both the tables (i.e., `link_table` and `item_table`), and the node is truncated
An LRU cache should have both get(key) and put(key, value) operations to manage its contents efficiently based on the principle of retaining the most recently used items and evicting the least recently used ones when necessary. Please correct me if my understanding is not correct.

2023-09-13 13:44 UTC, avranju commented on devdoc/lru_cache_design.md
> +`lru_cache` is a module that implements a Least Recently Used (LRU) cache using `clds_hash_table` and `doublylinkedlist` from `c_util`.
>`doublylinkedlist` from `c_util` [](http://example.com/codeflow?start=102&length=32)

Given that this cache lives in clds repo, is it OK for clds to take a dependency on c_util? As in, c_util doesn't depend on clds does it?

2023-09-13 14:02 UTC, avranju commented on devdoc/lru_cache_design.md
> +    LRUList ->> LRUList: Acquire an exclusive lock
>LRUList ->> LRUList: Acquire an exclusive lock [](http://example.com/codeflow?start=4&length=46)

Good thing Dan set us straight and moved this cache into the client because this lock means that all offload reads are going to be serialized. This may not be as much of a problem on the client side as it is likely to be on the service. I am not sure how EH uses the client, but I doubt that they do a lot of concurrent reads on the same client instance. Or even if they did, that the concurrency is so great that this serialization is likely to become a bottleneck.

2023-09-13 14:23 UTC, avranju commented on devdoc/lru_cache_design.md
> +### Eviction
>Eviction [](http://example.com/codeflow?start=4&length=8)

We should probably make provision for having a callback invoked whenever stuff gets evicted. This would allow us to have metrics in higher layers to track eviction (which would allow us to tune capacity).

2023-09-13 18:30 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +`lru_cache` is a module that implements a Least Recently Used (LRU) cache using `clds_hash_table` and `doublylinkedlist` from `c_util`.
Yes that is fine, see "/doc/wiki/dev/submodule dependencies.md" in the EBS repo for the dependency layout.

2023-09-13 18:34 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +    B[Acquire Lock]
> B[Acquire Lock] [](http://example.com/codeflow?start=3&length=16)

I have to wonder, if this is in CLDS (lock-less data structures), why are we wrapping the lock-less hash table with a lock :) ?

If we truly need the lock, would it be better to just have a non-threadsafe hashtable that we use because we are locking anyway?

2023-09-13 18:36 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +    B[Acquire Lock]
Although Dan's comment below makes sense about ONLY locking the linked list and using the hash table outside of the lock. So maybe you are going to address this in a later iteration.

2023-09-13 18:41 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +    LRUList ->> LRUList: Acquire an exclusive lock
Erm *cough cough*, Elastic Log chiming in here. We do many concurrent reads today.

There is a PBI to improve this so we would end up only doing multiple concurrent reads for a given request to different blocks (which should be in different partitions and thus different clients).

Maybe it's fine because the fix we need to make anyway, but just calling it out :)

2023-09-14 16:40 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +LRU Cache uses `clds_hash_tables`, a `srw_lock`, and a `doubly_linked_list`.
>clds_hash_tables [](http://example.com/codeflow?start=16&length=16)

likely should be singular now

2023-09-14 16:43 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +1.  The `table` stores the key and value `(void* key, CLDS_HASH_TABLE_ITEM* value)`. The `table` stores `DLIST_ENTRY` and `size` by crafting it in the form of `LRU_NODE` and storing this as a value i
>table` stores the key and value `(void* key, CLDS_HASH_TABLE_ITEM* value)`. The `table` stores `DLIST_ENTRY` [](http://example.com/codeflow?start=9&length=108)

This says the table stores two different things. Likely can be reworded in the second sentence like "the value stores the `DLIST_ENTRY`..." Or Just completely rephrase that second sentence as "The `CLDS_HASH_TABLE_ITEM` contains an `LRU_NODE` which has a `DLIST_ENTRY` and `size`."? Maybe needs to say something about the user content somewhere though.

2023-09-14 16:45 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +    B[Acquire Lock]
FYI, there is a `clds_singly_linked_list` (used internally by the hash table I think). Not sure if you really need the doubly linked list or if that could work.

2023-09-14 16:53 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +```
Can't we limit the locking a bit here to just be around the list?

```
    A --> C
    C --> D
    D -->|Yes| E
    D -->|No| F
    F --> G
    E --> G
    G --> B
    B --> H
    H --> I
    I --> J
    J --> K
```

2023-09-14 17:34 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +    B[Acquire Lock]
I'll even throw out a crazy idea:

`clds_singly_linked_list` already works for insert/delete. The missing piece is you want to evict the "tail", which means you need to walk the list to find it if it's not doubly-linked.

Well, what if you accept that eviction could be "slow" (walk the list) and we push it on another thread?

Then you could do the eviction by calling `clds_singly_linked_list_find` with a callback that just counts nodes until it reaches the eviction size and stores them in its `item_compare_context`.

Now you have a collection of nodes that should be evicted and you can do the normal removal.

2023-09-14 17:46 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +This operation retrieves items from the cache and rearranges the order in the `doubly_linked_list` by moving the found item to its head. It ensures that recently accessed items are placed at the fron
>rearranges the order in the `doubly_linked_list` [](http://example.com/codeflow?start=50&length=48)

I wonder if it would be possible to use clds_sorted_list for this? Or some modification of it. If the "item_key" was some always incrementing volatile number that is assigned, then the sorted list key compare was looking at that value, then maybe you can get a lock-less list of ordered items to evict.

In fact, eviction could maybe just be calling `clds_sorted_list_delete_key` for the older values.

Not sure if it's worth looking at this now or just putting it as a note in the improvements section.

2023-09-14 17:46 UTC, mattdurak approved these changes
:shipit:

2023-09-18 13:05 UTC, avranju commented on devdoc/lru_cache_design.md
> +LRU Cache uses `clds_hash_tables`, a `srw_lock`, and a `doubly_linked_list`.
>clds_hash_tables [](http://example.com/codeflow?start=16&length=16)

Nit: `clds_hash_table`. Maybe:

_LRU Cache uses a `clds_hash_table`_

2023-09-18 13:14 UTC, avranju commented on devdoc/lru_cache_design.md
> +To evict the least recently used item from the cache, the key from the tail of the `doubly_linked_list` is removed from the `table`, and the node is truncated from the `doubly_linked_list`. When an i
>truncated [](http://example.com/codeflow?start=149&length=9)

Removed?

2023-09-18 13:15 UTC, avranju commented on devdoc/lru_cache_design.md
> +1.  The `table` stores the key and value `(void* key, CLDS_HASH_TABLE_ITEM* value)`. The `table` stores `DLIST_ENTRY` and `size` by crafting it in the form of `LRU_NODE` and storing this as a value i
>The `table` stores `DLIST_ENTRY` and `size` by crafting it in the form of `LRU_NODE` and storing this as a value in the form of `CLDS_HASH_TABLE_ITEM`. [](http://example.com/codeflow?start=85&length=151)

Consider saying something like:

The `table` contains `LRU_NODE` instances as the value corresponding to the supplied keys. The `LRU_NODE` contains a `DLIST_ENTRY` which points to a node in the linked list. Do we store a pointer to the `LRU_NODE` in the linked list as well?

2023-09-18 13:17 UTC, avranju commented on devdoc/lru_cache_design.md
> +sequenceDiagram
Should this logic run in a loop till cache usage drops below desired usage?

2023-09-18 13:20 UTC, avranju commented on devdoc/lru_cache_design.md
> +One area of improvement lies in the management of the `doubly_linked_list`, which is currently protected by a lock. To further optimize concurrent access to the cache, a lock-free `doubly_linked_list
>a lock-free `doubly_linked_list` [](http://example.com/codeflow?start=168&length=32)

Another alternative could be having the eviction performed from a background thread (as discussed on the chat). Might be useful to capture the idea here so we can evaluate it later if need be.

2023-09-18 13:20 UTC, avranju approved these changes
:shipit:

2023-09-19 17:17 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    Cache ->> LRUList: Extract LRU_NODE from the item
To prevent race conditions and ensure data consistency, acquire a lock before reading shared data.

2023-09-19 17:17 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    E[Remove item from cache]
Couple of points: 

1. If an item already exists in the cache, instead of removing it and adding it again, it's more efficient to update its content after finding it. However, is there a specific reason why we can't do this with the clds_hash_table?

2. When an item is not present in the cache, it's advisable to first check if the current cache size (current_size) is equal to the capacity (capacity) before initiating the eviction logic. Eviction should only be considered when the cache is at its maximum capacity.

2023-09-19 18:45 UTC, mattdurak commented on devdoc/lru_cache_design.md
> +- Another potential enhancement involves moving `doubly_linked_list` updates to a background thread. Instead of immediately updating the list within cache operations like `get` we could use a queue f
>This might occasionally lead to extra waits during `put` operations [](http://example.com/codeflow?start=371&length=67)

I guess that depends on whether the LRU cache **must never exceed the capacity**, or if it's acceptable to temporarily exceed (so puts can go ahead and the eviction will eventually catch up).

2023-09-19 18:57 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    E[Remove item from cache]
For 2: Prior to invoking the "evict" function, we can explicitly highlight or specify the necessary details in the diagram?

2023-09-19 18:57 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    Cache ->> LRUList: Extract LRU_NODE from the item
Should not we make `current_size` atomic variable here, for the same reason.

2023-09-19 19:58 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    LRUList ->> LRUList: Acquire an exclusive lock
LRUList ->> LRUList: Acquire an exclusive lock should be before the ==> LRUList ->> LRUList: Check the item's position in the list ?

2023-09-19 20:16 UTC, ACKPaul commented on devdoc/lru_cache_design.md
> +    E[Remove item from cache]
Step 2: You can proceed with the insertion, and if the capacity exceeds its limit, then remove the oldest entry.

What I would have implemented in c++ (it is not thread safe), a toy example: 
```
class LRUCache {
    unordered_map<int,list<pair<int,int>>::iterator> umap; 
    list<pair<int,int>> que;
    int capacity; 
    
public:
    LRUCache(int capacity) {     
        this->capacity = capacity ; 
    }
    
    int get(int key) {
        auto it = umap.find(key);         
        if(it != umap.end()) {
            
            int val = it->second->second;  
            
            movetoFront(it);           
                      
            return val;             
        }
        
        return -1; 
        
    }
    
    void put(int key, int value) {
        
         auto it = umap.find(key); 
        
         if(it != umap.end()){
             it->second->second = value; 
             movetoFront(it);
         }else {
             
             umap[key] = que.insert(que.begin(),{key,value}); 
             
             if(capacity < que.size()){
                 auto li = que.back(); 
                 umap.erase(li.first); 
                 que.pop_back();                                         
             }                        
         }        
    }
    
    void movetoFront( unordered_map<int,list<pair<int,int>>::iterator>::iterator & it) {        
        int key = it->second->first; 
        int val = it->second->second;         
        que.erase(it->second);
        it->second = que.insert(que.begin(), {key,val});              
    }
};
```

2023-09-20 00:22 UTC, dcristoloveanu approved these changes
:shipit:

2023-09-20 02:25 UTC, merged